import com.egoriku.dependencies.versions.LibrariesVersion

object Libs {
    const val annotation = "androidx.annotation:annotation:${LibrariesVersion.annotation}"
    const val appcompat = "androidx.appcompat:appcompat:${LibrariesVersion.appcompat}"
    const val beagle = "com.github.pandulapeter.beagle:beagle:${LibrariesVersion.beagle}"
    const val browser = "androidx.browser:browser:${LibrariesVersion.browser}"
    const val cardView = "androidx.cardview:cardview:${LibrariesVersion.cardView}"
    const val circleImageView = "de.hdodenhof:circleimageview:${LibrariesVersion.circleImageView}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${LibrariesVersion.constraintLayout}"
    const val coreKtx = "androidx.core:core-ktx:${LibrariesVersion.coreKtx}"
    const val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${LibrariesVersion.coroutinesAndroid}"
    const val crashlytics = "com.crashlytics.sdk.android:crashlytics:${LibrariesVersion.crashlytics}"
    const val dagger = "com.google.dagger:dagger:${LibrariesVersion.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${LibrariesVersion.dagger}"
    const val firebaseAuth = "com.google.firebase:firebase-auth:${LibrariesVersion.firebaseAuth}"
    const val firebaseCore = "com.google.firebase:firebase-core:${LibrariesVersion.firebaseCore}"
    const val firebaseFirestoreKtx = "com.google.firebase:firebase-firestore-ktx:${LibrariesVersion.firebaseFirestore}"
    const val fragment = "androidx.fragment:fragment:${LibrariesVersion.fragment}"
    const val glide = "com.github.bumptech.glide:glide:${LibrariesVersion.glide}"
    const val glideCompiler = "com.github.bumptech.glide:compiler:${LibrariesVersion.glide}"
    const val junit = "junit:junit:${LibrariesVersion.junit}"
    const val koinAndroid = "org.koin:koin-android:${LibrariesVersion.koin}"
    const val koinAndroidExperimental = "org.koin:koin-androidx-ext:${LibrariesVersion.koin}"
    const val koinCore = "org.koin:koin-core:${LibrariesVersion.koin}"
    const val koinFragment = "koin-androidx-fragment:${LibrariesVersion.koin}"
    const val koinScope = "org.koin:koin-androidx-scope:${LibrariesVersion.koin}"
    const val koinViewModel = "org.koin:koin-androidx-viewmodel:${LibrariesVersion.koin}"
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${LibrariesVersion.kotlin}"
    const val leakCanary = "com.squareup.leakcanary:leakcanary-android:${LibrariesVersion.leakCanary}"
    const val lifecycleExtensions = "androidx.lifecycle:lifecycle-extensions:${LibrariesVersion.lifecycle}"
    const val liveDataKtx = "androidx.lifecycle:lifecycle-livedata-ktx:${LibrariesVersion.lifecycle}"
    const val material = "com.google.android.material:material:${LibrariesVersion.material}"
    const val pageIndicator = "com.ryanjeffreybrooks:indefinitepagerindicator:${LibrariesVersion.pageIndicator}"
    const val playCore = "com.google.android.play:core:${LibrariesVersion.playCore}"
    const val recyclerView = "androidx.recyclerview:recyclerview:${LibrariesVersion.recyclerView}"
    const val vectorDrawable = "androidx.vectordrawable:vectordrawable:${LibrariesVersion.vectorDrawable}"
    const val viewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${LibrariesVersion.lifecycle}"
    const val viewPager2 = "androidx.viewpager2:viewpager2:${LibrariesVersion.viewPager2}"
}
