package com.egoriku.ladyhappy.core.sharedmodel.key

const val EDIT_REQUEST_KEY = "EDIT_REQUEST_KEY"
const val EDIT_BUNDLE_RESULT_KEY = "EDIT_BUNDLE_RESULT_KEY"

const val DYNAMIC_FEATURE_REQUEST_KEY = "DYNAMIC_REQUEST_KEY"
const val DYNAMIC_FEATURE_BUNDLE_RESULT_KEY = "DYNAMIC_FEATURE_BUNDLE_RESULT_KEY"
