package com.egoriku.dependencies.versions

object LibrariesVersion {
    const val annotation = "1.1.0"
    const val appcompat = "1.1.0"
    const val beagle = "1.8.1"
    const val browser = "1.2.0"
    const val cardView = "1.0.0"
    const val constraintLayout = "2.0.0-beta4"
    const val coreKtx = "1.2.0"
    const val coroutinesAndroid = "1.3.5"
    const val circleImageView = "3.1.0"
    const val crashlytics = "2.10.1@aar"
    const val dagger = "2.27"
    const val firebaseAuth = "19.3.0"
    const val firebaseCore = "17.2.3"
    const val firebaseFirestore = "21.3.1"
    const val fragment = "1.2.3"
    const val glide = "4.11.0"
    const val junit = "4.13"
    const val koin = "2.1.5"
    const val kotlin = "1.3.71"
    const val leakCanary = "2.2"
    const val lifecycle = "2.2.0"
    const val material = "1.2.0-alpha05"
    const val pageIndicator = "1.0.10"
    const val playCore = "1.7.1"
    const val recyclerView = "1.1.0"
    const val vectorDrawable = "1.1.0"
    const val viewPager2 = "1.0.0"
}