package com.egoriku.dependencies.versions

object LibrariesVersion {
    const val annotation = "1.1.0"
    const val appcompat = "1.1.0"
    const val browser = "1.0.0"
    const val cardView = "1.0.0"
    const val constraintLayout = "2.0.0-beta2"
    const val coreKtx = "1.1.0"
    const val coroutinesAndroid = "1.3.1"
    const val crashlytics = "2.10.1@aar"
    const val dagger = "2.24"
    const val firebaseCore = "17.2.0"
    const val firestore = "21.1.1"
    const val fragment = "1.1.0"
    const val glide = "4.10.0"
    const val junit = "4.12"
    const val kotlin = "1.3.50"
    const val leakCanary = "2.0-beta-3"
    const val lifecycle = "2.1.0"
    const val material = "1.0.0"
    const val pageIndicator = "1.0.10"
    const val recyclerView = "1.0.0"
    const val vectorDrawable = "1.1.0"
}