package com.egoriku.dependencies.versions

object LibrariesVersion {
    const val annotation = "1.1.0"
    const val appcompat = "1.1.0"
    const val browser = "1.0.0"
    const val cardView = "1.0.0"
    const val constraintLayout = "2.0.0-beta3"
    const val coreKtx = "1.1.0"
    const val coroutinesAndroid = "1.3.2"
    const val circleImageView = "3.0.1"
    const val crashlytics = "2.10.1@aar"
    const val dagger = "2.25.2"
    const val firebaseCore = "17.2.1"
    const val firestore = "21.3.0"
    const val fragment = "1.1.0"
    const val glide = "4.10.0"
    const val junit = "4.12"
    const val koin = "2.1.0-alpha-7"
    const val kotlin = "1.3.61"
    const val leakCanary = "2.0"
    const val lifecycle = "2.2.0-rc02"
    const val material = "1.2.0-alpha02"
    const val pageIndicator = "1.0.10"
    const val recyclerView = "1.1.0"
    const val vectorDrawable = "1.1.0"
    const val viewPager2 = "1.0.0"
}