name: "Check TODO and create issue"

on: ["push"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@master"
    - name: "TODO to Issue"
      uses: "alstr/todo-to-issue-action@v4.1"
      id: "todo"
