package com.egoriku.core.constant

const val DYNAMIC_FEATURE_POST_CREATOR = "postCreator"

const val REQUEST_KEY_DYNAMIC_FEATURE = "REQUEST_KEY_DYNAMIC_FEATURE"
const val RESULT_KEY_DYNAMIC_FEATURE = "RESULT_KEY_DYNAMIC_FEATURE"